name: Build

on:
  push:
    tags:
    - 'v*.*.*'
    branches:
    - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build project
        run: msbuild ./PhysicsGame.sln /p:Configuration=Release
        
      - name: Create artifact directory
        run: mkdir ./artifact/PhysicsGame
        
      - name: Copy executable to artifact directory
        run: copy ./Build/PhysicsGame/Release/Win32/PhysicsGame.exe ./artifact/PhysicsGame/PhysicsGame.exe
        
      - name: Upload artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: PhysicsGame-artifact
          path: ./artifact/

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Create release
        uses: elgohr/Github-Release-Action@v5
        env:
          GH_TOKEN:  ${{ secrets.GITHUB_TOKEN }}
        with:
          title: Physics Game Release

      - name: Download artifact
        uses: actions/download-artifact@v5
        with: 
          name: PhysicsGame-artifact
          path:  ./artifact/

      - name: GitHub release  
        uses: fnkr/github-action-ghr@v1.3
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_COMPRESS: zip
          GHR_PATH: ./artifact/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
